### ISSUE TITLE
pcdet.version ModuleNotFoundError

### ISSUE THREAD

**Issue by CCorbinLEE** [KaAI-KMU/OpenPCDet-KaAI#1]
Traceback (most recent call last):
  File "/home/kaai/anaconda3/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/kaai/anaconda3/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/kaai/OpenPCDet-KaAI/pcdet/__init__.py", line 4, in <module>
    from .version import __version__
ModuleNotFoundError: No module named 'pcdet.version'

ImageSet generation을 하는 과정중에 생긴 오류입니다.

**Comment by IamJiyong** [comment]
setup 하셨나요?

**Comment by CCorbinLEE** [comment]
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/kaai/anaconda3/lib/python3.9/site-packages/scipy/spatial/_ckdtree.cpython-39-x86_64-linux-gnu.so)
그 셋업되있는 폴더로 해봤는데 이렇게 뜹니다.

**Comment by IamJiyong** [comment]
셋업되어있는 폴더가 무슨 뜻인가요?

**Comment by CCorbinLEE** [comment]
setup이 안된 폴더에서 하면 맨 위와같이 오류가 뜨고 setup이 된 폴더애서는 아래와 같이 뜨는데 그 install 과정에서 setup.py를 돌린 폴더를 말한것이였습니다!

**Comment by IamJiyong** [comment]
이 repository를 clone 하셔서 다시 setup 진행해주셔야 됩니다ㅎㅎ

**Comment by IamJiyong** [comment]
그리고 같은 가상환경에서 OpenPCDet을 두 개 setup을 못하는 걸로 알고있습니다.
그래서 만약 가상환경 A에서 OpenPCDet을 새로 setup 하신다면, 전에 A에서 사용하던 OpenPCDet은 경로가 꼬여 에러가 날겁니다.
지금 케이스에서는 상관 없으니까 참고만 해주시면 됩니다.

**Comment by CCorbinLEE** [comment]
다시 있는 openpcdet을 다 삭제하고 setup을 했는데도 똑같이 ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/kaai/anaconda3/lib/python3.9/site-packages/scipy/spatial/_ckdtree.cpython-39-x86_64-linux-gnu.so)
이 문제가 뜨는데 다른 컴퓨터에서 진행하는게 나을까요?

**Comment by CCorbinLEE** [comment]
일단 해결방법을 계속 찾고는 있습니다.

**Comment by IamJiyong** [comment]
command line부터 에러 처음부터 끝까지 다 올려주실 수 있나요?

**Comment by CCorbinLEE** [comment]
(base) kaai@kaai-MS-7D07:~/annotation_tool/OpenPCDet-KaAI$ python -m pcdet.datasets.kaai.kaai_dataset generate_imagesets tools/cfgs/dataset_configs/kaai_dataset.yaml 0
Traceback (most recent call last):
  File "/home/kaai/anaconda3/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/kaai/anaconda3/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/kaai/annotation_tool/OpenPCDet-KaAI/pcdet/datasets/__init__.py", line 8, in <module>
    from .dataset import DatasetTemplate
  File "/home/kaai/annotation_tool/OpenPCDet-KaAI/pcdet/datasets/dataset.py", line 8, in <module>
    from .augmentor.data_augmentor import DataAugmentor
  File "/home/kaai/annotation_tool/OpenPCDet-KaAI/pcdet/datasets/augmentor/data_augmentor.py", line 6, in <module>
    from . import augmentor_utils, database_sampler
  File "/home/kaai/annotation_tool/OpenPCDet-KaAI/pcdet/datasets/augmentor/augmentor_utils.py", line 5, in <module>
    from ...utils import box_utils
  File "/home/kaai/annotation_tool/OpenPCDet-KaAI/pcdet/utils/box_utils.py", line 5, in <module>
    from scipy.spatial import Delaunay
  File "/home/kaai/anaconda3/lib/python3.9/site-packages/scipy/spatial/__init__.py", line 105, in <module>
    from ._kdtree import *
  File "/home/kaai/anaconda3/lib/python3.9/site-packages/scipy/spatial/_kdtree.py", line 5, in <module>
    from ._ckdtree import cKDTree, cKDTreeNode
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/kaai/anaconda3/lib/python3.9/site-packages/scipy/spatial/_ckdtree.cpython-39-x86_64-linux-gnu.so)
이렇게 떴습니다!

**Comment by IamJiyong** [comment]
scipy를 삭제하고 다시 install 해보실래요?
pip uninstall scipy
pip install scipy

**Comment by CCorbinLEE** [comment]
오 해결됬습니다!
그 뒤에 패키지 임포트 안되는 거 다 삭제하고 깔았더니 segmentation fault error가 나왔습니다.
python -m pcdet.datasets.kaai.kaai_dataset generate_imagesets tools/cfgs/dataset_configs/kaai_dataset.yaml 0
Segmentation fault (core dumped)
보호된 메모리의 문제라고 하여 sudo를 넣고 강제로 실행했더니 /usr/bin/python: No module named pathlib
이미 pathlib이 깔려있다고 하는데 어떻게 해결해야할까요?
귀찮게 해드려 죄송합니다....

**Comment by IamJiyong** [comment]
아 readme에 설명을 안넣은거같은데
data/kaai/training/lidar 폴더를 생성하고 그 안에 pcd 파일들을 넣어야합니다
training 시에는 data/kaai/training/lable 폴더를 생성하고 그 안에 json 파일들을 넣어야합니다.

**Comment by CCorbinLEE** [comment]
![image](https://user-images.githubusercontent.com/127930494/226831241-25114f1a-1677-41b8-af2d-ab865fd50497.png)


이런식으로 폴더를 생성하고 pcd파일을 넣었습니다. 그 상태에서 돌릴려하니 Segmentation fault(core dumped)라는 오류가 자꾸 발생하네요..

**Comment by CCorbinLEE** [comment]
ImageSets라는 폴더가 없는것같아 이 부분도 추가시켜놓긴했습니다.

**Comment by IamJiyong** [comment]
오류 전문 볼수 있을까요?

**Comment by CCorbinLEE** [comment]
(base) kaai@kaai-MS-7D07:~/annotation_tool/OpenPCDet-KaAI$ python -m pcdet.datasets.kaai.kaai_dataset generate_imagesets tools/cfgs/dataset_configs/kaai_dataset.yaml 0
Segmentation fault (core dumped)
이런식으로 떴습니다!

**Comment by IamJiyong** [comment]
앞에 sudo를 붙이면 뭐라고 뜨나요?

**Comment by CCorbinLEE** [comment]
(base) kaai@kaai-MS-7D07:~/annotation_tool/OpenPCDet-KaAI$ sudo python -m pcdet.datasets.kaai.kaai_dataset generate_imagesets tools/cfgs/dataset_configs/kaai_dataset.yaml 0
[sudo] password for kaai: 
/usr/bin/python: No module named pathlib
이렇게 뜹니다!

**Comment by CCorbinLEE** [comment]
sudo python -m pcdet.datasets.kaai.kaai_dataset generate_imagesets tools/cfgs/dataset_configs/kaai_dataset.yaml 0
/usr/bin/python: No module named pcdet.datasets.kaai


이것저것 막 시도해봤더니 이런식으로 바뀌었습니다!

**Comment by CCorbinLEE** [comment]
(base) kaai@kaai-MS-7D07:~$ python -m pcdet.datasets.kaai.kaai_dataset generate_imagesets tools/cfgs/dataset_configs/kaai_dataset.yaml 0
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Segmentation fault (core dumped)

sudo를 제거했을경우는 다음과 같은 오류가 발생했습니다.
